### ISSUE TITLE
Dropdown Menu Styling

### ISSUE THREAD

**Issue by lihaohong6** [robalb/x86-64-playground#9]
![image](https://github.com/user-attachments/assets/ce7584f8-9439-40a2-b190-35f27f4ee309)

This dropdown menu is styled incorrectly. I'm guessing it's because I set Google Chrome to use dark mode, but switching back to light mode does not resolve the problem. The web page looks fine on Firefox.

User agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36`

**Comment by robalb** [comment]
Thanks, it should be fixed now. I was still using an unstyled element for that dropdown

**Comment by lihaohong6** [comment]
Thanks! The dropdown looks all good now.
